// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InterviewReady
{
    public partial class UserShoppingTable
    {
        public string Username { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}